routes/web.php
<?php


use App\Http\Controllers\Shared\MaintenanceController;
use App\Http\Controllers\Manager\StudentDataController;
use App\Http\Controllers\Shared\ContractController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Shared\AdvertismentController;
use App\Http\Controllers\Shared\HouseController;
use App\Http\Controllers\Shared\RoomController;
use App\Http\Controllers\testController;
use App\Http\Controllers\Manager\BlockedRoomController;
use App\Http\Controllers\Manager\SupervisorController;
use App\Http\Controllers\Shared\ConfirmationController;
use App\Http\Controllers\Shared\QuittanceController;
use App\Http\Controllers\Shared\SwitchRoomController;
use App\Http\Controllers\Student\OrderController;
use App\Http\Livewire\ManagerOrders;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;



Route::group(['middleware'=>'auth'],function(){
Route::get('/home',function(){

 if(Auth::user()->type=='admin'){
    return redirect('/admin');
 }
 if(Auth::user()->type=='student'){
    return redirect('/student');
 }
 if(Auth::user()->type=='manager'){
    return redirect('/manager');
 }
 if(Auth::user()->type=='supervisor'){
    return redirect('/supervisor');
 }
});
Route::group(['middleware'=>'role:admin','prefix'=>'admin','as'=>'admin.'],function(){
   Route::view('/','admin.admin');
   Route::resource('/houses',HouseController::class)->except('show');
   Route::resource('/houses/{house_id}',RoomController::class)->only(['index','store']);
   Route::resource('/rooms',RoomController::class)->only(['update','destroy']);
   Route::resource('/user',UserController::class);
 
});



Route::group(['middleware'=>'role:manager','prefix'=>'manager','as'=>'manager.'],function(){
   Route::view('/','manager.manager');
    Route::resource('/contract',ContractController::class)->only(['index','store','create','update']);
    Route::resource('/students',StudentDataController::class)->only(['index','store']);
    Route::post('/contract/{room_id}',[ContractController::class,'store']);
    Route::resource('/contract',ContractController::class)->only(['index','update']);
    Route::resource('/maintenance',MaintenanceController::class)->only(['index','update']);
    Route::resource('/quittance',QuittanceController::class)->only(['index','update']);
    Route::get('/houses/{house_id}/block/{room_id}',[BlockedRoomController::class,'index']);
    Route::post('/block/{room_id}',[BlockedRoomController::class,'blockRoom'])->name('block');
    Route::post('/unblock/{room_id}',[BlockedRoomController::class,'UnBlockedRoom'])->name('unblock');
    Route::resource('/houses',HouseController::class)->only(['index']);
    Route::resource('/houses/{house_id}',RoomController::class)->only(['index']);
    Route::view('/houses/{house_id}/{room_id}','manager.student_regstration');
    Route::resource('/switch_room', SwitchRoomController::class)->only(['index','update']);
    Route::post('/quittance_by_manager/{contract_id}',[QuittanceController::class,'quittance_by_manager'])->name('quittanceByManager');
    Route::resource('/supervisor', SupervisorController::class)->only(['index','update']);
    Route::get('/viewroom/{room_id}',ManagerOrders::class);
    Route::get('/viewstudent/{student_id}',ManagerOrders::class);
    Route::resource('/advertisments',AdvertismentController::class)->only(['index','store']);
});





Route::group(['middleware'=>'role:student','prefix'=>'student','as'=>'student.'],function(){
         Route::view('/','student.student');
         Route::resource('/houses',HouseController::class)->only(['index']);
         Route::resource('/houses/{house_id}', RoomController::class)->only(['index']);
         Route::post('/regestroom/{roomid}',[ContractController::class,'regestRoom']);
         Route::resource('/maintenance',MaintenanceController::class)->only(['store']);
         Route::get('/myOrder',[OrderController::class,'index'])->name('order');
         Route::resource('/quittance',QuittanceController::class)->only(['store']);
         Route::post('/switch_room/{room_id}',[SwitchRoomController::class,'store']);
         Route::resource('/advertisments',AdvertismentController::class)->only(['index']);
});

Route::group(['middleware'=>'role:supervisor','prefix'=>'supervisor','as'=>'supervisor.'],function(){
         Route::view('/','supervisor.supervisor');
         Route::resource('/maintenance',MaintenanceController::class)->only(['index','update']);
         Route::resource('/quittance',QuittanceController::class)->only(['index','update']);
         Route::resource('/switch_room',SwitchRoomController::class)->only(['index','update']);
         Route::resource('/advertisments',AdvertismentController::class)->only(['index']);
});

});


Route::redirect('/', '/login', 301);
Route::get('/test',[testController::class,'s']);

Route::get('/test',[testController::class,'index']);

resources/views/admin/admin.blade.php
<!DOCTYPE html>
<html dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- framework css file -->
    <  <link rel="stylesheet" href="{{ asset('css/framework.css') }}">
    <!-- main template css file -->
    <link rel="stylesheet" href="{{ asset('css/main.css') }}">
    <!-- render all elements normally -->
    <link rel="stylesheet" href="{{ asset('css/normalize.css') }}">
    <!-- font awesome library -->
    <link rel="stylesheet" href="{{ asset('css/all.min.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster+Two:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">

    <title>جامعة القلمون الخاصة</title>
</head>

<body>
    <div class="page d-flex ">
        <div class="sidebar  p-20 p-relative">
            <div class="logo">
                <img src="{{ asset('images/homoon.png') }}" alt="">          
          </div>
            <ul>
                <li>
                    <a class="active d-flex align-center fs-14  rad-6 p-10 " href="/">
                        <i class="fa-solid fa-sliders fa-fw"></i>
                        <span>الصفحة الرئيسية</span>
                    </a>
                </li>
                <li>
                    <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/admin/houses">
                        <i class="fa-solid fa-hotel fa-fw"></i>
                        <span>إدارة السكنات </span>
                    </a>
                </li>
                <li>
                    <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/admin/user">

                        <i class="fa-solid fa-users-gear fa-fw"></i>
                        <span> إدارة المستخدمين </span>
                    </a>
                    <li>
                       
                        <a href="javascript:{}" class=" d-flex align-center fs-14  rad-6 p-10 " onclick="document.getElementById('my_form').submit();">
    
                            <i class="fa-solid fa-right-from-bracket fa-fw"></i>
                            <span>  تسجيل خروج</span>
                        </a>
                        <form method="POST" action="{{ route('logout') }}" id="my_form" style="display: none">
                            @csrf
                        </form>
                    </li>

            </ul>

        </div>
        <div class="content">
            <!-- start head -->
            <!-- end head -->
            <h1 class="p-relative">الصفحة الرئيسية</h1>
            <div class="wrapper d-grid gap-20 ">
                <div class="welcome bg-white rad-10 ">
                    <div class="intro p-20 d-flex space-between bg-eee">
                        <div>
                            <h2 class="m-0 ">أهلا بك </h2>
                            <p class="c-gray mt-5 ">admin </p>
                        </div>
                        <img src="../images/download.png" alt="">
                    </div>
                </div>
            </div>

        </div>
    </div>
    
</body>

</html>

resources/views/admin/houses.blade.php
<!DOCTYPE html>
<html dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- framework css file -->
    <link rel="stylesheet" href="{{ asset('css/framework.css') }}">
    <!-- main template css file -->
    <link rel="stylesheet" href="{{ asset('css/main.css') }}">
    <!-- render all elements normally -->
    <link rel="stylesheet" href="{{ asset('css/normalize.css') }}">
    <!-- font awesome library -->
    <link rel="stylesheet" href="{{ asset('css/all.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/houses.css') }}">

    <link rel="stylesheet" href="{{ asset('css/create-house.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster+Two:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    <script src="{{ asset('vendor/sweetalert/sweetalert.all.js') }}"></script>

    <title>جامعة القلمون الخاصة</title>
</head>

<body>

    <div class="page d-flex  ">
        <div class="sidebar  p-20 p-relative">
            <h3 class="p-relative txt-c mt-0">
                النبراس
            </h3>
            <ul>
                <li>
                    <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/">
                        <i class="fa-solid fa-sliders fa-fw"></i>
                        <span>الصفحة الرئيسية</span>
                    </a>
                </li>
                <li>
                    <a class="active d-flex align-center fs-14  rad-6 p-10 " href="/admin/houses">
                        <i class="fa-solid fa-hotel fa-fw"></i>
                        <span>إدارة السكنات </span>
                    </a>
                </li>
                <li>
                    <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/admin/user">

                        <i class="fa-solid fa-users-gear fa-fw"></i>
                        <span> إدارة المستخدمين </span>
                    </a>
                    <li>
                       
                        <a href="javascript:{}" class=" d-flex align-center fs-14  rad-6 p-10 " onclick="document.getElementById('my_form').submit();">
    
                            <i class="fa-solid fa-right-from-bracket fa-fw"></i>
                            <span>  تسجيل خروج</span>
                        </a>
                        <form method="POST" action="{{ route('logout') }}" id="my_form" style="display: none">
                            @csrf
                        </form>
                    </li>

            </ul>

        </div>
        <div class="content ">
            <!-- start head -->
            <!-- end head -->
            <h1 class="p-relative">إدارة السكن</h1>
            <div class="wrapper d-flex gap-20 ">
                <!-- <div class="welcome bg-white rad-10 "> -->
                        
                <div class="intro p-20   bg-eee">
                  
                    @foreach ($houses as $house)
                    <div class="container">
                        <div class="card" >

                            <div class="contentBx">
                                <h2>{{ $house->id }}</h2>
                                <a href="/admin/houses/{{$house->id}}" style="margin:10px" title="دخول" id="enter">
                                    <i class="fa-sharp fa-solid fa-arrow-right"></i>
                                </a>
                                <div>
                                    <a href="javascript:{}"  title="تعديل" onclick="openForm('{{ $house->id }}')">
                                        <i class="fa-solid fa-pencil fa-fw"></i>

                                    </a>
                                    <a  href="javascript:{}" onclick="confirm('{{ $house->id }}d')" title="حذف">
                                        <i class="fa-solid fa-trash fa-fw"></i>
                                    </a>
                                <form id="{{ $house->id }}d" method="POST" action='{{ route('admin.houses.destroy',$house->id) }}' style="all: revert">
                                @csrf
                                @method('DELETE')   
                               </form>
                                </div>
 
                            </div>
                        </div>
                    </div>
               
                    @endforeach

                    <div class="container">
                        <div class="card-add">

                            <div class="contentBx-add">
                                <h2>إضافة سكن</h2>
                                <a href="javascript:{}" style="margin:10px" title="إضافة سكن" id="enter" onclick="openForm('add-form')" >
                                    <i class="fa-solid fa-plus "></i>
                                </a>
                              
                            </div>
                        </div>
                    </div>



                </div>


            </div>
            
        </div>
    </div>
    @foreach  ($houses as $house)
    <form method="POST" action="{{route('admin.houses.update',$house->id)  }}"   style="display: none" class="add-form popupForm" id="{{$house->id}}">
        @csrf
        @method('PUT')
        <h3>تعديل سكن</h3>
        <button class="closeModal" onclick="colseForm('{{$house->id}}')" type="button"> </button>
        <input type="text" placeholder="اسم السكن"  name="house_id" required value="{{$house->id}}">

        <select class="gender" name="gender" value="{{ $house->gender }}"> 
            <option value="male" @if ( $house->gender=="male")
                selected              
            @endif>ذكر</option>
            <option value="female"@if ( $house->gender=="female")
                selected              
            @endif>أنثى</option>
        </select>
        <button class="add-button" type="submit">تعديل</button>

    </form>
    @endforeach
    <form method="POST" action="{{ route('admin.houses.store') }}"  id="add-form" style="display: none" class="add-form popupForm">
        @csrf
        <h3> إضافة سكن</h3>
        <button class="closeModal" onclick="colseForm('add-form')" type="button"> </button>
  
        <input type="text" placeholder="اسم السكن"  name="house_id" required >

        <select class="gender" name="gender"> 
            <option value="" selected hidden>اختر جنس السكن </option>
            <option value="male">ذكر</option>
            <option value="female">أنثى</option>
        </select>
        <button class="add-button" type="submit"> اضافة</button>

    </form>
    <script type="text/javascript">
    function openForm(id){
        document.getElementById(id).style.display = "block";
        document.body.id='popedup';
    }
    function colseForm(id){
      document.getElementById(id).style.display = "none";
        document.body.id='';
    }
    function confirm(house_id){
  var form = document.getElementById(house_id);
  Swal.fire({
      title: "حذف هذ السكن",
      text: " لايمكنك التراجع",
      background:"var(--black-color)",
              color:"var(--white-color)",
      showCancelButton: true,
      confirmButtonColor: "var(--red-color)",
      confirmButtonText: "تم", 
      cancelButtonText: 'أغلاق',
      closeOnConfirm: false
  }).then((result) => {
  /* Read more about isConfirmed, isDenied below */
  if (result.isConfirmed) {
   form.submit();
  } 
});
return false;
}
    
      </script>
@include('sweetalert::alert');
</body>

resources/views/admin/users.blade.php
<!DOCTYPE html>
<html dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- framework css file -->
    <link rel="stylesheet" href="{{ asset('css/framework.css') }}">
    <!-- main template css file -->
    <link rel="stylesheet" href="{{ asset('css/main.css') }}">
    <!-- render all elements normally -->
    <link rel="stylesheet" href="{{ asset('css/normalize.css') }}">
    <!-- font awesome library -->
    <link rel="stylesheet" href="{{ asset('css/all.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/users.css') }}">
    <link rel="stylesheet" href="{{ asset('css/create-user.css') }}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster+Two:ital,wght@0,400;0,700;1,400;1,700&display=swap"
        rel="stylesheet">
    <script src="{{ asset('vendor/sweetalert/sweetalert.all.js') }}"></script>
    @livewireStyles
    <title>جامعة القلمون الخاصة</title>
</head>

<body>
    <div class="page d-flex ">
        <div class="sidebar  p-20 p-relative">
            <div class="logo">
                <img src="{{ asset('images/homoon.png') }}" alt="">
            </div>
            <ul>
                <li>
                    <a class="d-flex align-center fs-14  rad-6 p-10 " href="/">
                        <i class="fa-solid fa-sliders fa-fw"></i>
                        <span>الصفحة الرئيسية</span>
                    </a>
                </li>
                <li>
                    <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/admin/houses">
                        <i class="fa-solid fa-hotel fa-fw"></i>
                        <span>إدارة السكنات </span>
                    </a>
                </li>
                <li>
                    <a class="active  d-flex align-center fs-14  rad-6 p-10 " href="/admin/user">

                        <i class="fa-solid fa-users-gear fa-fw"></i>
                        <span> إدارة المستخدمين </span>
                    </a>
                    <li>
                       
                        <a href="javascript:{}" class=" d-flex align-center fs-14  rad-6 p-10 " onclick="document.getElementById('my_form').submit();">
    
                            <i class="fa-solid fa-right-from-bracket fa-fw"></i>
                            <span>  تسجيل خروج</span>
                        </a>
                        <form method="POST" action="{{ route('logout') }}" id="my_form" style="display: none">
                            @csrf
                        </form>
                    </li>

            </ul>

        </div>
        <div class="content">
            <!-- start head -->
            <!-- end head -->
            <h1 class="p-relative">إدارة المستخدمين</h1>

            <div class="wrapper d-grid gap-20 ">
                <div class="welcome bg-white rad-10 ">
                    <div class="intro p-20 d-flex space-between bg-eee">
                        <button class="user">
                            <a href="javascript:{}" onclick="openForm('add-form')"> إنشاء مستخدم جديد
                                <i class="fa-solid fa-plus fa-fw"></i></a>
                        </button>

                        <livewire:users>

                    </div>
                </div>
            </div>

        </div>
    </div>
    @foreach ($users as $user)
    <form method="POST" action="{{ route('admin.user.update',$user->id) }}" class="popupForm add_user_form"
        style="display: none" id="{{ $user->id }}">
        @csrf
        @method('PUT')
        <h3> تعديل مستخدم</h3>
        <button class="closeModal" onclick="colseForm('{{ $user->id }}')" type="button"> </button>
        <input type="text" placeholder="أدخل اسم المستخدم: " id="username" name="name" value="{{ $user->name }}"
            required>
        <select class=" gender" name="type" value="{{ $user->type }}">
            <option value="manager" @if ( $user->type=='manager' )
                selected
            @endif>مدير</option>
            <option value="supervisor" @if ( $user->type=='supervisor' )
                selected
            @endif>مشرف</option>
            <option value="admin"value="supervisor" @if ( $user->type=='admin' )
                selected
            @endif>أدمن</option>
        </select>
        <select name="gender" class=" gender" value=" {{ $user->gender }}">

            <option value="male" @if ( $user->gender=='male' )
                selected
            @endif>ذكر</option>
            <option value="female" @if ( $user->gender=='female' )
                selected
            @endif>أنثى</option>
        </select>
        <button type="submit" class="add_user_button"> تعديل </button>
    </form>
    @endforeach
    <form method="POST" action="{{ route('admin.user.store') }}" class="popupForm add_user_form" style="display: none"
        id="add-form">
        @csrf
        <h3> إضافة مستخدم</h3>
        <button class="closeModal" onclick="colseForm('add-form')" type="button"> </button>
        <input type="text" placeholder="أدخل اسم المستخدم: " name="name" required>
      
        <select class=" gender" name="type">
            <option value="" selected hidden> اختر دور المستخدم</option>
            <option value="manager">مدير</option>
            <option value="supervisor">مشرف</option>
            <option value="admin">أدمن</option>
        </select>
      
        <select name="gender" class=" gender">
            <option value="" selected hidden> اختر جنس المستخدم</option>
            <option value="male">ذكر</option>
            <option value="female">أنثى</option>
        </select>
        <button type="submit" class="add_user_button"> إضافة </button>
    </form>
    

    @include('sweetalert::alert');

    <script type="text/javascript">
        function openForm(id){
          console.log(id);
          document.getElementById(id).style.display = "block";
          document.body.id='popedup';
      }
      function colseForm(id){
        document.getElementById(id).style.display = "none";
          document.body.id='';
      }
        
     
  
    </script>
    <script>
        function confirm(user_id){
          console.log("hi");
          var form = document.getElementById(user_id);
         Swal.fire({
              title: "حذف هذا المستخدم",
              text: " لايمكنك التراجع",
                background:"var(--black-color)",
              color:"var(--white-color)",
              showCancelButton: true,
              confirmButtonColor: "var(--red-color)",
              confirmButtonText: "حذف", 
              closeOnConfirm: false
          }).then((result)=>{
              if(result.isConfirmed){
                  form.submit();
              }
          });
      return false;
      }
    </script>
 
    @livewireScripts

</body>