routes/web.php
<?php


use App\Http\Controllers\Shared\MaintenanceController;
use App\Http\Controllers\Manager\StudentDataController;
use App\Http\Controllers\Shared\ContractController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Shared\AdvertismentController;
use App\Http\Controllers\Shared\HouseController;
use App\Http\Controllers\Shared\RoomController;
use App\Http\Controllers\testController;
use App\Http\Controllers\Manager\BlockedRoomController;
use App\Http\Controllers\Manager\SupervisorController;
use App\Http\Controllers\Shared\ConfirmationController;
use App\Http\Controllers\Shared\QuittanceController;
use App\Http\Controllers\Shared\SwitchRoomController;
use App\Http\Controllers\Student\OrderController;
use App\Http\Livewire\ManagerOrders;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;



Route::group(['middleware'=>'auth'],function(){
Route::get('/home',function(){

 if(Auth::user()->type=='admin'){
    return redirect('/admin');
 }
 if(Auth::user()->type=='student'){
    return redirect('/student');
 }
 if(Auth::user()->type=='manager'){
    return redirect('/manager');
 }
 if(Auth::user()->type=='supervisor'){
    return redirect('/supervisor');
 }
});
Route::group(['middleware'=>'role:admin','prefix'=>'admin','as'=>'admin.'],function(){
   Route::view('/','admin.admin');
   Route::resource('/houses',HouseController::class)->except('show');
   Route::resource('/houses/{house_id}',RoomController::class)->only(['index','store']);
   Route::resource('/rooms',RoomController::class)->only(['update','destroy']);
   Route::resource('/user',UserController::class);
 
});



Route::group(['middleware'=>'role:manager','prefix'=>'manager','as'=>'manager.'],function(){
   Route::view('/','manager.manager');
    Route::resource('/contract',ContractController::class)->only(['index','store','create','update']);
    Route::resource('/students',StudentDataController::class)->only(['index','store']);
    Route::post('/contract/{room_id}',[ContractController::class,'store']);
    Route::resource('/contract',ContractController::class)->only(['index','update']);
    Route::resource('/maintenance',MaintenanceController::class)->only(['index','update']);
    Route::resource('/quittance',QuittanceController::class)->only(['index','update']);
    Route::get('/houses/{house_id}/block/{room_id}',[BlockedRoomController::class,'index']);
    Route::post('/block/{room_id}',[BlockedRoomController::class,'blockRoom'])->name('block');
    Route::post('/unblock/{room_id}',[BlockedRoomController::class,'UnBlockedRoom'])->name('unblock');
    Route::resource('/houses',HouseController::class)->only(['index']);
    Route::resource('/houses/{house_id}',RoomController::class)->only(['index']);
    Route::view('/houses/{house_id}/{room_id}','manager.student_regstration');
    Route::resource('/switch_room', SwitchRoomController::class)->only(['index','update']);
    Route::post('/quittance_by_manager/{contract_id}',[QuittanceController::class,'quittance_by_manager'])->name('quittanceByManager');
    Route::resource('/supervisor', SupervisorController::class)->only(['index','update']);
    Route::get('/viewroom/{room_id}',ManagerOrders::class);
    Route::get('/viewstudent/{student_id}',ManagerOrders::class);
    Route::resource('/advertisments',AdvertismentController::class)->only(['index','store']);
});





Route::group(['middleware'=>'role:student','prefix'=>'student','as'=>'student.'],function(){
         Route::view('/','student.student');
         Route::resource('/houses',HouseController::class)->only(['index']);
         Route::resource('/houses/{house_id}', RoomController::class)->only(['index']);
         Route::post('/regestroom/{roomid}',[ContractController::class,'regestRoom']);
         Route::resource('/maintenance',MaintenanceController::class)->only(['store']);
         Route::get('/myOrder',[OrderController::class,'index'])->name('order');
         Route::resource('/quittance',QuittanceController::class)->only(['store']);
         Route::post('/switch_room/{room_id}',[SwitchRoomController::class,'store']);
         Route::resource('/advertisments',AdvertismentController::class)->only(['index']);
});

Route::group(['middleware'=>'role:supervisor','prefix'=>'supervisor','as'=>'supervisor.'],function(){
         Route::view('/','supervisor.supervisor');
         Route::resource('/maintenance',MaintenanceController::class)->only(['index','update']);
         Route::resource('/quittance',QuittanceController::class)->only(['index','update']);
         Route::resource('/switch_room',SwitchRoomController::class)->only(['index','update']);
         Route::resource('/advertisments',AdvertismentController::class)->only(['index']);
});

});


Route::redirect('/', '/login', 301);
Route::get('/test',[testController::class,'s']);

Route::get('/test',[testController::class,'index']);

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Laravel\Scout\Searchable;


class Student extends Model
{
    use HasFactory;
    use SoftDeletes;
    use Searchable;
    
    protected $table='students';
    protected $fillable=['university_id','student_name','gender','disapproval'];
    protected $primaryKey='university_id';
    public function getContracts(){
        return $this->hasMany(Contract::class);
    }
    public function getContract(){
        return $this->hasMany(Contract::class,'student_id')->where('contract_state','=','active_now')->first();
    }
    public function getActiveContract(){
        return $this->hasMany(Contract::class,'student_id')->where('contract_state','=','active_now');
    }
    public function getMaintenances(){
        return $this->hasManyThrough(Maintenance::class,Contract::class,'student_id','contract_id');
    }
    public function getQuittances(){
        return $this->hasManyThrough(Quittance::class,Contract::class,'student_id','contract_id');
    }
    public function getExcep(){
        return $this->hasMany(Excep::class);
    }
    public function getStudentData(){
        return $this->hasOne(StudentData::class);
    }
    public function getSwitchRoom(){
        return $this->hasManyThrough(SwitchRoom::class,Contract::class,'student_id','contract_id');
    }
    public function hasRoom(){
        return $this->hasMany(Contract::class,'student_id')->where(function ($query) {
            $query->where('contract_state', '=', 'active_now')
                  ->orWhere('contract_state', '=', 'in_progress');
        })->get()->count()>0;
    }
    public function toSearchableArray()
    {
        return [
            'university_id' => $this->university_id,
            'student_name' => $this->student_name,
        ];
    }
    public function hasSwitchRoom()
    {
        return $this->getSwitchRoom()->where(function ($query) {
            $query->where('switch_room_state', '=', 'in_supervisor')
            ->orWhere('switch_room_state', '=', 'in_manager');
        })->get()->count()>0;
    }
    public function hasMaintenance()
    {
        return $this->getMaintenances()->where(function ($query) {
            $query->where('maintenace_state', '=', 'in_supervisor')
            ->orWhere('maintenace_state', '=', 'in_manager');
        })->get()->count()>0;
    }
    public function hasQuittance(){
        return $this->getQuittances->where(function ($query){
            $query->where('quittance_state','=','in_supervisor')->orWhere('quittance_state','=', 'in_manager');
        })->count()>0;
    }
    public function hasOrder(){
        return $this->hasQuittance() || $this->hasMaintenance() || $this->hasSwitchRoom();
    }
    public function hasActiveRoom(){
        return $this->getActiveContract()->count()>0;
    }
}

app/Http/Controllers/Student/OrderController.php
<?php

namespace App\Http\Controllers\Student;

use App\Http\Controllers\Controller;
use App\Models\Contract;
use App\Models\Maintenance;
use App\Models\Quittance;
use App\Models\Student;
use App\Models\SwitchRoom;
use Doctrine\DBAL\Schema\View;
use Illuminate\Contracts\View\View as ViewView;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class OrderController extends Controller
{
    public function index(){
        if(Auth()->user()->type=="student"){
        $student=Student::find(Auth()->user()->user_id);
        $hasOrder=$student->hasOrder();
        $hasActiveRoom=$student->hasActiveRoom();
       return View('student.order')->with(['hasOrder'=>$hasOrder,'hasActiveRoom'=>$hasActiveRoom]);}
    }
}

resources/views/student/advertisments.blade.php
<!DOCTYPE html>
<html dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- framework css file -->
    <link rel="stylesheet" href="{{ asset('css/framework.css') }}">
    <!-- main template css file -->
    <link rel="stylesheet" href="{{ asset('css/main.css') }}">
    <!-- render all elements normally -->
    <link rel="stylesheet" href="{{ asset('css/normalize.css') }}">
    <!-- font awesome library -->
    <link rel="stylesheet" href="{{ asset('css/all.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/advertisment.css') }}">
    <link rel="stylesheet" href="{{ asset('css/create-adv.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster+Two:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    @livewireStyles
    <title>جامعة القلمون الخاصة</title>
</head>

<body>
    <div class="page d-flex ">
        <div class="sidebar  p-20 p-relative">
            <div class="logo">
                <img src="{{ asset('images/homoon.png') }}" alt="">          
          </div>
          <ul>
            <li>
                <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/student">
                    <i class="fa-solid fa-sliders fa-fw"></i>
                    <span>الصفحة الرئيسية</span>
                </a>
            </li>
            <li>
                <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/student/houses">
                    <i class="fa-solid fa-hotel fa-fw"></i>
                    <span> السكنات</span>
                </a>
            </li>
            <li>
                <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/student/myOrder">
                    <i class="fa-solid fa-heart"></i>
                    <span>  طلباتي </span>
                </a>
            </li>
            <li>
                <a class="active d-flex align-center fs-14  rad-6 p-10 " href="/student/advertisments">

                    <i class="fa-solid fa-bullhorn"></i>
                    <span> الإعلانات </span>
                </a>
            </li>
            <li>
                
                <a href="javascript:{}" class=" d-flex align-center fs-14  rad-6 p-10 " onclick="document.getElementById('my_form').submit();">

                    <i class="fa-solid fa-right-from-bracket fa-fw"></i>
                    <span>  تسجيل خروج</span>
                </a>
                <form method="POST" action="{{ route('logout') }}" id="my_form" style="display: none">
                    @csrf
                </form>
            </li>
        </ul>

        </div>
        <div class="content">
            <!-- start head -->
            <!-- end head -->
            <h1 class="p-relative"> الإعلانات </h1>
            <div class="wrapper d-grid gap-20 ">
                <div class="welcome bg-white rad-10 ">
                    <div class="intro p-20 d-flex space-between bg-eee">
                        <div class="latest_news p-20 bg-white rad-10 txt-c">
                            
                                @livewire('advirtesment')
                            



                        </div>


                    </div>
                </div>
            </div>

        </div>
    </div>
    @foreach  ($advetisments as $advertisment)
    <form method="GET" action="/student/advertisments/{{ $advertisment->id }}"   style="display: none" class="adv-form popupForm" id="{{ $advertisment->id}}">
        @csrf
        <h3> {{ $advertisment->title }}</h3>
        <button class="closeModal" onclick="colseForm('{{$advertisment->id}}')" type="button"> </button>
        <label for="username"  >إلى كافة الطلاب</label>
        <label for="username"  >{{ $advertisment->message }} </label>

    </form>
    @endforeach
    <script type="text/javascript">
        function openForm(id){
            document.getElementById(id).style.display = "block";
            document.body.id='popedup';
        }
        function colseForm(id){
          document.getElementById(id).style.display = "none";
            document.body.id='';
        }
    </script>
     @livewireScripts
</body>

</html>

resources/views/student/myhouse.blade.php
<!DOCTYPE html>
<html dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- framework css file -->
    <link rel="stylesheet" href="{{ asset('css/framework.css') }}">
    <!-- main template css file -->
    <link rel="stylesheet" href="{{ asset('css/main.css') }}">
    <!-- render all elements normally -->
    <link rel="stylesheet" href="{{ asset('css/normalize.css') }}">
    <!-- font awesome library -->
    <link rel="stylesheet" href="{{ asset('css/all.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/houses.css') }}">


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster+Two:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">

    <title>جامعة القلمون الخاصة</title>
</head>

<body>

    <div class="page d-flex  ">
        <div class="sidebar  p-20 p-relative">
            <div class="logo">
                <img src="{{ asset('images/homoon.png') }}" alt="">          
          </div>
            <ul>
                <li>
                    <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/student">
                        <i class="fa-solid fa-sliders fa-fw"></i>
                        <span> الصفحة الرئيسية</span>
                    </a>
                </li>
                <li>
                    <a class="active d-flex align-center fs-14  rad-6 p-10 " href="/student/houses">
                        <i class="fa-solid fa-hotel fa-fw"></i>
                        <span> السكنات</span>
                    </a>
                </li>
                <li>
                    <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/student/myOrder">

                        <i class="fa-solid fa-heart"></i>
                        <span>  طلباتي </span>
                    </a>
                </li>
                <li>
                    <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/student/advertisments">
    
                        <i class="fa-solid fa-bullhorn"></i>
                        <span> الإعلانات </span>
                    </a>
                </li>
                <li>
                    <form method="POST" action="{{ route('logout') }}" id="my_form">
                        @csrf
                    <a href="javascript:{}" class=" d-flex align-center fs-14  rad-6 p-10 " onclick="document.getElementById('my_form').submit();">

                        <i class="fa-solid fa-right-from-bracket fa-fw"></i>
                        <span>  تسجيل خروج</span>
                    </a>
                    </form>
                </li>
            </ul>

        </div>
        <div class="content ">
            <!-- start head -->
            <!-- end head -->
            <h1 class="p-relative"> السكنات</h1>
            <div class="wrapper d-flex gap-20 ">
                <!-- <div class="welcome bg-white rad-10 "> -->
                <div class="intro p-20   bg-eee">
                    @foreach ($houses as $house)
                    <div class="container">
                        <div class="card">

                            <div class="contentBx">
                                <h2>{{ $house->id }}</h2>

                                <a href="/student/houses/{{ $house->id }}" style="margin:10px" id="enter">
                                    دخول
                                    
                                </a>


                            </div>
                        </div>
                    </div>
                    @endforeach






                </div>


            </div>
        </div>
@include('sweetalert::alert');
</body>

resources/views/student/myrooms.blade.php
<!DOCTYPE html>
<html dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- main template css file -->

    <link rel="stylesheet" href="{{ asset('css/framework.css') }}">
    <link rel="stylesheet" href="{{ asset('css/main.css') }}">
    <!-- render all elements normally -->
    <link rel="stylesheet" href="{{ asset('css/normalize.css') }}">
    <!-- font awesome library -->
    <link rel="stylesheet" href="{{ asset('css/all.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/rooms.css') }}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster+Two:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    @livewireStyles
    <script src="{{ asset('vendor/sweetalert/sweetalert.all.js') }}"></script>
    <title>جامعة القلمون الخاصة</title>
</head>

<body>

    <div class="page d-flex  ">
        <div class="sidebar  p-20 p-relative">
            <div class="logo">
                <img src="{{ asset('images/homoon.png') }}" alt="">
            </div>
            <ul>
                <li>
                    <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/student">
                        <i class="fa-solid fa-sliders fa-fw"></i>
                        <span> الصفحة الرئيسية</span>
                    </a>
                </li>
                <li>
                    <a class="active d-flex align-center fs-14  rad-6 p-10 " href="/student/houses">
                        <i class="fa-solid fa-hotel fa-fw"></i>
                        <span> السكنات</span>
                    </a>
                </li>
                <li>
                    <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/student/myOrder">

                        <i class="fa-solid fa-heart"></i>
                        <span> طلباتي </span>
                    </a>
                </li>
                <li>
                    <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/student/advertisments">
    
                        <i class="fa-solid fa-bullhorn"></i>
                        <span> الإعلانات </span>
                    </a>
                </li>
                <li>
                    <form method="POST" action="{{ route('logout') }}" id="my_form">
                        @csrf
                        <a href="javascript:{}" class=" d-flex align-center fs-14  rad-6 p-10 "
                            onclick="document.getElementById('my_form').submit();">

                            <i class="fa-solid fa-right-from-bracket fa-fw"></i>
                            <span> تسجيل خروج</span>
                        </a>
                    </form>
                </li>
            </ul>

        </div>
        <div class="content ">
            <!-- start head -->
            <!-- end head -->
            <h1 class="p-relative"> السكنات</h1>

            @livewire('rooms')

        </div>
    </div>
    @include('sweetalert::alert')
    @livewireScripts
    <script type="text/javascript">
        function confirm(room_id){
  
    var form = document.getElementById(room_id);
    Swal.fire({
        title: "هل انت متأكد",
        text: "لا يمكنك الغاء الطلب بعد التأكيد",
        background:"var(--black-color)",
          color:"var(--white-color)",
        showCancelButton: true,
        confirmButtonColor:" var(--move-color)",
        confirmButtonText: "تم", 
        closeOnConfirm: false,
        cancelButtonText: 'إغلاق',
    }).then((result)=>{
        if (result.isConfirmed) {
            form.submit();
        }
    });
return false;
}


    </script>
 
</body>

resources/views/student/order.blade.php
<!DOCTYPE html>
<html dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- framework css file -->
    <link rel="stylesheet" href="{{ asset('css/framework.css') }}">
    <!-- main template css file -->
    <link rel="stylesheet" href="{{ asset('css/main.css') }}">
    <!-- render all elements normally -->
    <link rel="stylesheet" href="{{ asset('css/normalize.css') }}">
    <!-- font awesome library -->
    <link rel="stylesheet" href="{{ asset('css/all.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/users.css') }}">


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster+Two:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{{ asset('vendor/sweetalert/sweetalert.all.js') }}"></script>
    @livewireStyles
    <title>جامعة القلمون الخاصة</title>
</head>

<body>
    <div class="page d-flex ">
        <div class="sidebar  p-20 p-relative">
            <div class="logo">
                <img src="{{ asset('images/homoon.png') }}" alt="">          
          </div>
          <ul>
            <li>
                <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/student">
                    <i class="fa-solid fa-sliders fa-fw"></i>
                    <span>الصفحة الرئيسية</span>
                </a>
            </li>
            <li>
                <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/student/houses">
                    <i class="fa-solid fa-hotel fa-fw"></i>
                    <span> السكنات</span>
                </a>
            </li>
            <li>
                <a class="active d-flex align-center fs-14  rad-6 p-10 " href="/student/myOrder">
                    <i class="fa-solid fa-heart"></i>
                    <span>  طلباتي </span>
                </a>
            </li>
            <li>
                <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/student/advertisments">

                    <i class="fa-solid fa-bullhorn"></i>
                    <span> الإعلانات </span>
                </a>
            </li>
            <li>
                
                <a href="javascript:{}" class=" d-flex align-center fs-14  rad-6 p-10 " onclick="document.getElementById('my_form').submit();">

                    <i class="fa-solid fa-right-from-bracket fa-fw"></i>
                    <span>  تسجيل خروج</span>
                </a>
                <form method="POST" action="{{ route('logout') }}" id="my_form" style="display: none">
                    @csrf
                </form>
            </li>
        </ul>

        </div>
        <div class="content">
            <!-- start head -->
            <!-- end head -->
            <h1 class="p-relative">طلباتي</h1>

            <div class="wrapper d-grid gap-20 ">
                
                <div class="welcome bg-white rad-10 ">
                    @if(!$hasOrder && $hasActiveRoom)
                    <select id="select" class="swal2-select" style="background-color: var(--black-color); height:50px;color:var(--white-color);hover:var(--move-color)" onchange=""> 
                        <option>أضافة طلب</option>
                       <option value="1"> صيانة </option>
                       <option value="2">براءة ذمة</option>
                       <option value="3">تبديل</option>
                    </select>
                
                    @endif
                    <form class="order-form" method="POST" action="{{ route('student.maintenance.store') }}" style="display: none" id="maintenance">
                        @csrf
                    </form>
                
             
              
          
                <form method="POST" action="{{ route('student.quittance.store') }}" id="quit"  style="display: none">
                @csrf
                
                </form>
                    <div class="intro p-20 d-flex space-between bg-eee">
                        @if ($hasActiveRoom)
               
                        <livewire:orders>
                        @else
                        <h3>نحن بانتظارك لأن تحصل على غرفة اولاً</h3>
                        @endif
                      
                    </div>
                </div>
            </div>
    @include('sweetalert::alert')
    <script>
        $("#select").change(function () {
  if ($(this).val() == 1) {
    confirm2();
  }
  else if($(this).val() == 2){
    confirm();
  }
  else if($(this).val() == 3){
 
    window.location.assign('/student/houses');
  }
});
    </script>
    <script>
        function confirm2(){
      
      var form = document.getElementById("maintenance");
      console.log(form);
      Swal.fire({
          title: " اضف معلومات الطلب ",
          background:"var(--black-color)",
          color:"var(--white-color)",
          html: `   <textarea   id="description" class="swal2-input" placeholder="معلومات الطلب" required style="height: 150px;width: 298px">`,
          showCancelButton: true,
          confirmButtonColor: "var(--move-color)",
          confirmButtonText: "تم", 
          cancelButtonText: 'أغلاق',
          closeOnConfirm: false,
          preConfirm: () => {
    const description = Swal.getPopup().querySelector('#description').value
    if (!description) {
      Swal.showValidationMessage(`الرجاء ادخال جميع المعلومات المطلوبة`)
    }
    return {description:description}
    }
   
      }).then((result) => {
    if(result.isConfirmed){
    var description = document.createElement("input");
    description.value= `${result.value.description}`.trim();
    description.name="description";
    description.style.display="none";
    form.appendChild(description);
   form.submit();}
})
    return false;
    }
    
        </script>
        <script>
        function confirm(){
          
            var form = document.getElementById("quit");
            Swal.fire({
                title: "هل انت متأكد",
                text: "لا يمكنك الغاء الطلب بعد التأكيد",
                background:"var(--black-color)",
          color:"var(--white-color)",
                showCancelButton: true,
                confirmButtonColor:" var(--move-color)",
                confirmButtonText: "تم", 
                closeOnConfirm: false,
                cancelButtonText: 'إغلاق',
            }).then((result)=>{
                if (result.isConfirmed) {
                    form.submit();
                }
            });
        return false;
        }
        
        
        </script>
        @livewireScripts
</body>

resources/views/student/student.blade.php
<!DOCTYPE html>
<html dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- framework css file -->
    <link rel="stylesheet" href="{{ asset('css/framework.css') }}">
    <!-- main template css file -->
    <link rel="stylesheet" href="{{ asset('css/main.css') }}">
    <!-- render all elements normally -->
    <link rel="stylesheet" href="{{ asset('css/normalize.css') }}">
    <!-- font awesome library -->
    <link rel="stylesheet" href="{{ asset('css/all.min.css') }}">


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster+Two:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">

    <title>جامعة القلمون الخاصة</title>
</head>

<body>
    <div class="page d-flex ">
        <div class="sidebar  p-20 p-relative">
            <div class="logo">
                <img src="{{ asset('images/homoon.png') }}" alt="">          
          </div>
            <ul>
                <li>
                    <a class="active d-flex align-center fs-14  rad-6 p-10 " href="/student">
                        <i class="fa-solid fa-sliders fa-fw"></i>
                        <span>الصفحة الرئيسية</span>
                    </a>
                </li>
                <li>
                    <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/student/houses">
                        <i class="fa-solid fa-hotel fa-fw"></i>
                        <span> السكنات</span>
                    </a>
                </li>
                <li>
                    <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/student/myOrder">
                        <i class="fa-solid fa-heart"></i>
                        <span>  طلباتي </span>
                    </a>
                </li>
                <li>
                    <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/student/advertisments">

                        <i class="fa-solid fa-bullhorn"></i>
                        <span> الإعلانات </span>
                    </a>
                </li>
                <li>
                    
                    <a href="javascript:{}" class=" d-flex align-center fs-14  rad-6 p-10 " onclick="document.getElementById('my_form').submit();">

                        <i class="fa-solid fa-right-from-bracket fa-fw"></i>
                        <span>  تسجيل خروج</span>
                    </a>
                    <form method="POST" action="{{ route('logout') }}" id="my_form" style="display: none">
                        @csrf
                    </form>
                </li>
            </ul>

        </div>
        <div class="content">
            <!-- start head -->
            <!-- end head -->
            <h1 class="p-relative">الصفحة الرئيسية</h1>
            <div class="wrapper d-grid gap-20 ">
                <div class="welcome bg-white rad-10 ">
                    <div class="intro p-20 d-flex space-between bg-eee">
                        <div>
                            <h2 class="m-0 ">أهلا بك </h2>
                            <p class="c-gray mt-5 ">student </p>
                        </div>
                        <img src="../images/download.png" alt="">
                    </div>
                </div>
            </div>

        </div>
    </div>