routes/web.php
<?php


use App\Http\Controllers\Shared\MaintenanceController;
use App\Http\Controllers\Manager\StudentDataController;
use App\Http\Controllers\Shared\ContractController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Shared\AdvertismentController;
use App\Http\Controllers\Shared\HouseController;
use App\Http\Controllers\Shared\RoomController;
use App\Http\Controllers\testController;
use App\Http\Controllers\Manager\BlockedRoomController;
use App\Http\Controllers\Manager\SupervisorController;
use App\Http\Controllers\Shared\ConfirmationController;
use App\Http\Controllers\Shared\QuittanceController;
use App\Http\Controllers\Shared\SwitchRoomController;
use App\Http\Controllers\Student\OrderController;
use App\Http\Livewire\ManagerOrders;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;



Route::group(['middleware'=>'auth'],function(){
Route::get('/home',function(){

 if(Auth::user()->type=='admin'){
    return redirect('/admin');
 }
 if(Auth::user()->type=='student'){
    return redirect('/student');
 }
 if(Auth::user()->type=='manager'){
    return redirect('/manager');
 }
 if(Auth::user()->type=='supervisor'){
    return redirect('/supervisor');
 }
});
Route::group(['middleware'=>'role:admin','prefix'=>'admin','as'=>'admin.'],function(){
   Route::view('/','admin.admin');
   Route::resource('/houses',HouseController::class)->except('show');
   Route::resource('/houses/{house_id}',RoomController::class)->only(['index','store']);
   Route::resource('/rooms',RoomController::class)->only(['update','destroy']);
   Route::resource('/user',UserController::class);
 
});



Route::group(['middleware'=>'role:manager','prefix'=>'manager','as'=>'manager.'],function(){
   Route::view('/','manager.manager');
    Route::resource('/contract',ContractController::class)->only(['index','store','create','update']);
    Route::resource('/students',StudentDataController::class)->only(['index','store']);
    Route::post('/contract/{room_id}',[ContractController::class,'store']);
    Route::resource('/contract',ContractController::class)->only(['index','update']);
    Route::resource('/maintenance',MaintenanceController::class)->only(['index','update']);
    Route::resource('/quittance',QuittanceController::class)->only(['index','update']);
    Route::get('/houses/{house_id}/block/{room_id}',[BlockedRoomController::class,'index']);
    Route::post('/block/{room_id}',[BlockedRoomController::class,'blockRoom'])->name('block');
    Route::post('/unblock/{room_id}',[BlockedRoomController::class,'UnBlockedRoom'])->name('unblock');
    Route::resource('/houses',HouseController::class)->only(['index']);
    Route::resource('/houses/{house_id}',RoomController::class)->only(['index']);
    Route::view('/houses/{house_id}/{room_id}','manager.student_regstration');
    Route::resource('/switch_room', SwitchRoomController::class)->only(['index','update']);
    Route::post('/quittance_by_manager/{contract_id}',[QuittanceController::class,'quittance_by_manager'])->name('quittanceByManager');
    Route::resource('/supervisor', SupervisorController::class)->only(['index','update']);
    Route::get('/viewroom/{room_id}',ManagerOrders::class);
    Route::get('/viewstudent/{student_id}',ManagerOrders::class);
    Route::resource('/advertisments',AdvertismentController::class)->only(['index','store']);
});





Route::group(['middleware'=>'role:student','prefix'=>'student','as'=>'student.'],function(){
         Route::view('/','student.student');
         Route::resource('/houses',HouseController::class)->only(['index']);
         Route::resource('/houses/{house_id}', RoomController::class)->only(['index']);
         Route::post('/regestroom/{roomid}',[ContractController::class,'regestRoom']);
         Route::resource('/maintenance',MaintenanceController::class)->only(['store']);
         Route::get('/myOrder',[OrderController::class,'index'])->name('order');
         Route::resource('/quittance',QuittanceController::class)->only(['store']);
         Route::post('/switch_room/{room_id}',[SwitchRoomController::class,'store']);
         Route::resource('/advertisments',AdvertismentController::class)->only(['index']);
});

Route::group(['middleware'=>'role:supervisor','prefix'=>'supervisor','as'=>'supervisor.'],function(){
         Route::view('/','supervisor.supervisor');
         Route::resource('/maintenance',MaintenanceController::class)->only(['index','update']);
         Route::resource('/quittance',QuittanceController::class)->only(['index','update']);
         Route::resource('/switch_room',SwitchRoomController::class)->only(['index','update']);
         Route::resource('/advertisments',AdvertismentController::class)->only(['index']);
});

});


Route::redirect('/', '/login', 301);
Route::get('/test',[testController::class,'s']);

Route::get('/test',[testController::class,'index']);

app/Http/Controllers/Manager/BlockedRoomController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use App\Models\Room;
use Illuminate\Http\Request;

class BlockedRoomController extends Controller
{
    public function blockRoom(Request $request,$room_id)
    {
        $room=Room::find($room_id);
        $room->update([
            'blocked_now' =>true,
            'blocked_reason' => $request->input('block_reason')
     ]);
    return redirect()->back()->with('success','تم حجب الغرفة بنجاح');
    }
    public function UnBlockedRoom($room_id)
    {
        $room=Room::find($room_id);
        $room->update([
            'blocked_now' =>false,
            'blocked_reason' => null
     ]);
     return redirect()->back()->with('success','تم إلغاء حجب الغرفة بنجاح');
    }
}

app/Http/Controllers/Manager/StudentDataController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use App\Imports\StudentDataImport;
use App\Models\Student;
use App\Models\StudentData;
use App\Models\User;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Maatwebsite\Excel\Facades\Excel;

class StudentDataController extends Controller
{
   
    public function index()
    {
        $students=Student::search(request('student-search'))->get();
      // $students=Student::all();
        return view('manager.students')->with(['students'=>$students]);
    }
    public function generateUsersFromExcel(){
        $studentsDatas=StudentData::all();
        foreach($studentsDatas as $data){
            User::firstOrCreate(['user_id'=>$data->university_id],['password'=>Hash::make($data->university_id),'name'=>$data->name,'type'=>'student','gender'=>$data->gender]);
            Student::firstOrcreate(['university_id'=>$data->university_id],['student_name'=>$data->name,'gender'=>$data->gender,'disapproval'=>false]);
        }
    }
    public function store(Request $request)
    {
        StudentData::truncate();
        try{
        Excel::import(new StudentDataImport,$request->file);}
        catch(Exception $e){
            return redirect()->back()->with('errors','أن هذ الملف غير صالح للعملية');
        }
        $this->generateUsersFromExcel();
        return redirect()->back()->with('success','تمت العملية بنجاح');
    }


   

 
}

app/Http/Controllers/Manager/SupervisorController.php
<?php

namespace App\Http\Controllers\Manager;
use App\Http\Controllers\Controller;
use App\Models\House;
use App\Models\Supervisor;
use App\Models\User;
use Illuminate\Http\Request;

class SupervisorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //  $supervisors=Supervisor::all();
      //  $femaleSupervisors=User::where('type','=','supervisor')->where('gender','=','female')->get();
      //  $maleSupervisors=User::where('type','=','supervisor')->where('gender','=','male')->get();
        $supervisors=User::where('type','=','supervisor')->get();
    
        $femaleHouses=House::where('gender','=','female')->get();
        $maleHouses=House::where('gender','=','male')->get();
        return view('manager.supervisors')->with(['supervisors'=>$supervisors,'femaleHouses'=>$femaleHouses,'maleHouses'=>$maleHouses]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
   //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request,User $user)
    {
        $supervisor=new Supervisor();
        $supervisor->user_id=$user->id;
        $supervisor->house_id=$request->input('house_id');
        $supervisor->save();
        return redirect()->back()->with('success','تم إضافة المشرف بنجاح');
       /* if($request->input('femaleSupervisor')==null)
        {
            $supervisor->user_id=$request->input('maleSupervisor'); 
        }
        else
        {
            $supervisor->user_id=$request->input('femaleSupervisor');
        }*/
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Supervisor $supervisor,House $house)
    {
        
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,  $user_id)
    {
       $supervisor=Supervisor::where('user_id',$user_id)->first();
        $supervisor->house_id=$request->input('house_id');
        $supervisor->save();
  
    return redirect()->route('manager.supervisor.index')->with('success','تم تعديل سكن المشرف بنجاح');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Supervisor $supervisor)
    {
        $supervisor->delete();
        return redirect()->route('manager.supervisor.index')->with('success','تم حذف المشرف بنجاح');
    }
}

resources/views/manager/advertisment.blade.php
<!DOCTYPE html>
<html dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- framework css file -->
    <link rel="stylesheet" href="{{ asset('css/framework.css') }}">
    <!-- main template css file -->
    <link rel="stylesheet" href="{{ asset('css/main.css') }}">
    <!-- render all elements normally -->
    <link rel="stylesheet" href="{{ asset('css/normalize.css') }}">
    <!-- font awesome library -->
    <link rel="stylesheet" href="{{ asset('css/all.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/advertisment.css') }}">
    <link rel="stylesheet" href="{{ asset('css/create-adv.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster+Two:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    <script src="{{ asset('vendor/sweetalert/sweetalert.all.js') }}"></script>
    @livewireStyles
    <title>جامعة القلمون الخاصة</title>

</head>

<body>
   
    <div class="page d-flex ">
        <div class="sidebar  p-20 p-relative">
            <div class="logo">
                <img src="{{ asset('images/homoon.png') }}" alt="logo">
            </div>
            <ul>
                <li>
                    <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/">
                        <i class="fa-solid fa-sliders fa-fw " ></i>
                        <span>الصفحة الرئيسية</span>
                    </a>
                </li>
                <li>
                    <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/manager/houses">
                        <i class="fa-solid fa-hotel fa-fw"></i>
                        <span>السكنات </span>
                    </a>
                </li>
                <li>
                    <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/manager/students">

                        <i class="fa-solid fa-people-line fa-fw"></i>
                        <span> الطلاب</span>
                    </a>
                </li>
                <li>
                    <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/manager/supervisor">

                        <i class="fa-solid fa-users"></i>
                        <span>مشرفي الوحدات السكنية</span>
                    </a>
                </li>
            
                <li>
                    <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/manager/contract">

                        <i class="fa-brands fa-readme fa-fw"></i>
                        <span> طلب التسجيل</span>
                    </a>
                </li>
               
                <li>
                    <a class="d-flex align-center fs-14  rad-6 p-10 " href="/manager/switch_room">

                        <i class="fa-solid fa-shuffle"></i>
                        <span> طلب التبديل</span>
                    </a>
                </li>
                <li>
                    <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/manager/quittance">

                        <i class="fa-solid fa-person-walking-arrow-right"></i>
                        <span> طلب براءة الذمة</span>
                    </a>
                </li>
                <li>
                    <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/manager/maintenance">

                        <i class="fa-sharp fa-solid fa-wrench"></i>
                        <span> طلب  الصيانة</span>
                    </a>
                </li>
                <li>
                    <a class=" d-flex align-center fs-14  rad-6 p-10 " href="comfirmation.html">

                        <i class="fa-solid fa-circle-check"></i>
                        <span> طلب التثبيت</span>
                    </a>
                </li>
                <li>
                    <a class="active d-flex align-center fs-14  rad-6 p-10 " href="/manager/advertisments">

                        <i class="fa-solid fa-bullhorn"></i>
                        <span> الإعلانات </span>
                    </a>
                </li>
                <li>
                  
                    <a href="javascript:{}" class=" d-flex align-center fs-14  rad-6 p-10 " onclick="document.getElementById('my_form').submit();">

                        <i class="fa-solid fa-right-from-bracket fa-fw"></i>
                        <span>  تسجيل خروج</span>
                    </a>
                    <form method="POST" action="{{ route('logout') }}" id="my_form" style="display: none">
                        @csrf
                    </form>
                </li>

            </ul>

        </div>
        
        <div class="content">
            <!-- start head -->
            <!-- end head -->
            <h1 class="p-relative"> الإعلانات </h1>
            <div class="wrapper d-grid gap-20 ">
               @livewire('advirtesment')
            </div>

        </div>
    </div>
    @foreach  ($advetisments as $advertisment)
    <form method="GET" action="/manager/advertisments/{{ $advertisment->id }}"   style="display: none; background-color: white" class="adv-form popupForm" id="{{ $advertisment->id}}" >
        @csrf
        <h3 style="color: black"> {{ $advertisment->title }}</h3>
        <button class="closeModal"  onclick="colseForm('{{$advertisment->id}}')" type="button"> </button>
        @if ($advertisment->addressed_to=='all')
        <label for="username"  style="color: black">إلى كافة الطلاب والمشرفين</label>
        @elseif($advertisment->addressed_to=='student')
        <label for="username" style="color: black" >إلى كافة الطلاب </label>
        @elseif($advertisment->addressed_to=='supervisor')
        <label for="username"  style="color: black">إلى كافةالمشرفين</label>
        @endif
        <label for="username" style="color: black" >{{ $advertisment->message }} </label>

    </form>
    @endforeach
    <form method="POST" action="{{ route('manager.advertisments.store') }}"  id="adv-form" style="display: none" class="adv-form popupForm">
        @csrf
        <h3> إضافة إعلان</h3>
        <button class="closeModal" onclick="colseForm('adv-form')" type="button"> </button>
        <label for="username"  >عنوان الإعلان</label>
        <input type="text" placeholder=" عنوان الإعلان"  name="title" required >
        <label for="username"  >محتوى الإعلان</label>
        <textarea placeholder=" محتوى الإعلان"  name="message" required class="message"></textarea>
        <label for="username"  >لمن موجه هذا الإعلان</label>
        <select class="addressed_to" name="addressed_to" > 
            <option value="all ">المشرفين والطلاب</option>
            <option value="student">الطلاب</option>
            <option value="supervisor">المشرفين</option>
        </select>
        <button class="adv-button" type="submit"> نشر الإعلان</button>
    </form>
    <script type="text/javascript">
        function openForm(id){
            document.getElementById(id).style.display = "block";
            document.body.id='popedup';
        }
        function colseForm(id){
          document.getElementById(id).style.display = "none";
            document.body.id='';
        }
    </script>
 @include('sweetalert::alert');
 @livewireScripts
</body>

</html>

resources/views/manager/hoses.blade.php
<!DOCTYPE html>
<html dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- framework css file -->
    <link rel="stylesheet" href="{{ asset('css/framework.css') }}">
    <!-- main template css file -->
    <link rel="stylesheet" href="{{ asset('css/main.css') }}">
    <!-- render all elements normally -->
    <link rel="stylesheet" href="{{ asset('css/normalize.css') }}">
    <!-- font awesome library -->
    <link rel="stylesheet" href="{{ asset('css/all.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/houses.css') }}">


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster+Two:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">

    <title>جامعة القلمون الخاصة</title>
</head>

<body>

    <div class="page d-flex  ">
        <div class="sidebar  p-20 p-relative">
            <div class="logo">
                <img src="{{ asset('images/homoon.png') }}" alt="">          
          </div>
          <ul>
            <li>
                <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/">
                    <i class="fa-solid fa-sliders fa-fw " ></i>
                    <span>الصفحة الرئيسية</span>
                </a>
            </li>
            <li>
                <a class="active d-flex align-center fs-14  rad-6 p-10 " href="/manager/houses">
                    <i class="fa-solid fa-hotel fa-fw"></i>
                    <span>السكنات </span>
                </a>
            </li>
            <li>
                <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/manager/students">

                    <i class="fa-solid fa-people-line fa-fw"></i>
                    <span> الطلاب</span>
                </a>
            </li>
            <li>
                <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/manager/supervisor">

                    <i class="fa-solid fa-users"></i>
                    <span>مشرفي الوحدات السكنية</span>
                </a>
            </li>
        
            <li>
                <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/manager/contract">

                    <i class="fa-brands fa-readme fa-fw"></i>
                    <span> طلب التسجيل</span>
                </a>
            </li>
           
            <li>
                <a class="d-flex align-center fs-14  rad-6 p-10 " href="/manager/switch_room">

                    <i class="fa-solid fa-shuffle"></i>
                    <span> طلب التبديل</span>
                </a>
            </li>
            <li>
                <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/manager/quittance">

                    <i class="fa-solid fa-person-walking-arrow-right"></i>
                    <span> طلب براءة الذمة</span>
                </a>
            </li>
            <li>
                <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/manager/maintenance">

                    <i class="fa-sharp fa-solid fa-wrench"></i>
                    <span> طلب  الصيانة</span>
                </a>
            </li>
            <li>
                <a class=" d-flex align-center fs-14  rad-6 p-10 " href="comfirmation.html">

                    <i class="fa-solid fa-circle-check"></i>
                    <span> طلب التثبيت</span>
                </a>
            </li>
            <li>
                <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/manager/advertisments">

                    <i class="fa-solid fa-bullhorn"></i>
                    <span> الإعلانات </span>
                </a>
            </li>
            <li>
              
                <a href="javascript:{}" class=" d-flex align-center fs-14  rad-6 p-10 " onclick="document.getElementById('my_form').submit();">

                    <i class="fa-solid fa-right-from-bracket fa-fw"></i>
                    <span>  تسجيل خروج</span>
                </a>
                <form method="POST" action="{{ route('logout') }}" id="my_form" style="display: none">
                    @csrf
                </form>
            </li>

        </ul>

        </div>


        <div class="content ">
            <!-- start head -->
            <!-- end head -->
            <h1 class="p-relative">السكنات</h1>
            <div class="wrapper d-flex gap-20 ">
                
                <!-- <div class="welcome bg-white rad-10 "> -->
                <div class="intro p-20   bg-eee">
                    @foreach ($houses as $house)
                    <div class="container">
                        <div class="card">

                            <div class="contentBx">
                                <h2>{{ $house->id }}</h2>

                                <a href="/manager/houses/{{ $house->id }}" style="margin:10px" id="enter">
                                    دخول
                                    
                                </a>


                            </div>
                        </div>
                    </div>
                    @endforeach







                </div>


            </div>
        </div>

</body>

resources/views/manager/student_regstration.blade.php
<!DOCTYPE html>
<html dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- main template css file -->
    
    <link rel="stylesheet" href="{{ asset('css/framework.css') }}">
    <link rel="stylesheet" href="{{ asset('css/main.css') }}">
    <!-- render all elements normally -->
    <link rel="stylesheet" href="{{ asset('css/normalize.css') }}">
    <!-- font awesome library -->
    <link rel="stylesheet" href="{{ asset('css/all.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/studentregestration.css') }}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster+Two:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>

    <title>جامعة القلمون الخاصة</title>
</head>

<body>

    <div class="page d-flex  ">
        <div class="sidebar  p-20 p-relative">
            <div class="logo">
                <img src="{{ asset('images/homoon.png') }}" alt="">          
          </div>
          <ul>
            <li>
                <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/">
                    <i class="fa-solid fa-sliders fa-fw " ></i>
                    <span>الصفحة الرئيسية</span>
                </a>
            </li>
            <li>
                <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/manager/houses">
                    <i class="fa-solid fa-hotel fa-fw"></i>
                    <span>السكنات </span>
                </a>
            </li>
            <li>
                <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/manager/students">

                    <i class="fa-solid fa-people-line fa-fw"></i>
                    <span> الطلاب</span>
                </a>
            </li>
            <li>
                <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/manager/supervisor">

                    <i class="fa-solid fa-users"></i>
                    <span>مشرفي الوحدات السكنية</span>
                </a>
            </li>
        
            <li>
                <a class="active d-flex align-center fs-14  rad-6 p-10 " href="/manager/contract">

                    <i class="fa-brands fa-readme fa-fw"></i>
                    <span> طلب التسجيل</span>
                </a>
            </li>
           
            <li>
                <a class="d-flex align-center fs-14  rad-6 p-10 " href="/manager/switch_room">

                    <i class="fa-solid fa-shuffle"></i>
                    <span> طلب التبديل</span>
                </a>
            </li>
            <li>
                <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/manager/quittance">

                    <i class="fa-solid fa-person-walking-arrow-right"></i>
                    <span> طلب براءة الذمة</span>
                </a>
            </li>
            <li>
                <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/manager/maintenance">

                    <i class="fa-sharp fa-solid fa-wrench"></i>
                    <span> طلب  الصيانة</span>
                </a>
            </li>
            <li>
                <a class=" d-flex align-center fs-14  rad-6 p-10 " href="comfirmation.html">

                    <i class="fa-solid fa-circle-check"></i>
                    <span> طلب التثبيت</span>
                </a>
            </li>
            <li>
                <a class=" d-flex align-center fs-14  rad-6 p-10 " href="/manager/advertisments">

                    <i class="fa-solid fa-bullhorn"></i>
                    <span> الإعلانات </span>
                </a>
            </li>
            <li>
              
                <a href="javascript:{}" class=" d-flex align-center fs-14  rad-6 p-10 " onclick="document.getElementById('my_form').submit();">

                    <i class="fa-solid fa-right-from-bracket fa-fw"></i>
                    <span>  تسجيل خروج</span>
                </a>
                <form method="POST" action="{{ route('logout') }}" id="my_form" style="display: none">
                    @csrf
                </form>
            </li>

        </ul>

        </div>

        <div class="content ">
            <!-- start head -->
            <!-- end head -->
            <h1 class="p-relative"> تسجيل الطالب</h1>
            <div class="wrapper d-flex gap-20 ">
                <!-- <div class="welcome bg-white rad-10 "> -->
                <div class="intro p-20   bg-eee">

                    <form  id="regestrationForm" method="POST" action="{{route('manager.contract.store',last(request()->segments()) )  }}">
                        @csrf
                        <h3> تسجيل الطالب</h3>
                        <label for="username">اسم الطالب</label>
                        <input type="text" placeholder="اسم الطالب"   name="student_name">
                        <label for="username" >رقم الطالب</label>
                        <input type="number" placeholder="20201113"  name='student_id'>
                        <div class="container">
                            <div class="selector">
                                <div class="selecotr-item">
                                    <input type="radio" id="radio1" name="type" class="selector-item_radio" checked onclick="hide()" value="1">
                                    <label for="radio1" class="selector-item_label">جديد </label>
                                </div>

                                <div class="selecotr-item">
                                    <input type="radio" id="radio2" name="type" class="selector-item_radio" onclick="hide()" value="0">
                                    <label for="radio2" class="selector-item_label"> قديم</label>
                                </div>
                                <div class="selecotr-item">
                                    <input type="radio" id="radio3" name="type" class="selector-item_radio" onclick="show()" value="2">
                                    <label for="radio3" class="selector-item_label">مستثنى </label>
                                </div>
                            </div>
                        </div>
                        <textarea class="field-area" placeholder="معلومات الاستثناء:" id="s" style="display: none" name="desc"></textarea>
                        <button type="submit"> تسجيل </button>

                    </form>


                </div>
           


            </div>


        </div>
    </div>
    @include('sweetalert::alert')
    <script>
        function show() {
            document.getElementById('s').style.display = "block";
        }

        function hide() {
            document.getElementById('s').style.display = "none";
        }
    </script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
   <script type="text/javascript">
$(function () 
{
    var $regestrationForm=$('#regestrationForm');
        $regestrationForm.validate(
            {
                rules:{
                    student_name:{
                       required:true
                    },
                    student_id:{
                       required:true,
                       min:200010000,
                       max:202310000
                    }
                },
                messages:{
                    student_name:{
                       required:'يجب إدخال اسم الطالب'
                    },
                    student_id:{
                       required:'يجب إدخال رقم الطالب',
                       min:'الرقم الجامعي للطالب غير صحيح',
                       max:'الرقم الجامعي للطالب غير صحيح'
                    }
                }
            }
        );
  
});
    </script>
</body>