routes/web.php
<?php


use App\Http\Controllers\Shared\MaintenanceController;
use App\Http\Controllers\Manager\StudentDataController;
use App\Http\Controllers\Shared\ContractController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Shared\AdvertismentController;
use App\Http\Controllers\Shared\HouseController;
use App\Http\Controllers\Shared\RoomController;
use App\Http\Controllers\testController;
use App\Http\Controllers\Manager\BlockedRoomController;
use App\Http\Controllers\Manager\SupervisorController;
use App\Http\Controllers\Shared\ConfirmationController;
use App\Http\Controllers\Shared\QuittanceController;
use App\Http\Controllers\Shared\SwitchRoomController;
use App\Http\Controllers\Student\OrderController;
use App\Http\Livewire\ManagerOrders;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;



Route::group(['middleware'=>'auth'],function(){
Route::get('/home',function(){

 if(Auth::user()->type=='admin'){
    return redirect('/admin');
 }
 if(Auth::user()->type=='student'){
    return redirect('/student');
 }
 if(Auth::user()->type=='manager'){
    return redirect('/manager');
 }
 if(Auth::user()->type=='supervisor'){
    return redirect('/supervisor');
 }
});
Route::group(['middleware'=>'role:admin','prefix'=>'admin','as'=>'admin.'],function(){
   Route::view('/','admin.admin');
   Route::resource('/houses',HouseController::class)->except('show');
   Route::resource('/houses/{house_id}',RoomController::class)->only(['index','store']);
   Route::resource('/rooms',RoomController::class)->only(['update','destroy']);
   Route::resource('/user',UserController::class);
 
});



Route::group(['middleware'=>'role:manager','prefix'=>'manager','as'=>'manager.'],function(){
   Route::view('/','manager.manager');
    Route::resource('/contract',ContractController::class)->only(['index','store','create','update']);
    Route::resource('/students',StudentDataController::class)->only(['index','store']);
    Route::post('/contract/{room_id}',[ContractController::class,'store']);
    Route::resource('/contract',ContractController::class)->only(['index','update']);
    Route::resource('/maintenance',MaintenanceController::class)->only(['index','update']);
    Route::resource('/quittance',QuittanceController::class)->only(['index','update']);
    Route::get('/houses/{house_id}/block/{room_id}',[BlockedRoomController::class,'index']);
    Route::post('/block/{room_id}',[BlockedRoomController::class,'blockRoom'])->name('block');
    Route::post('/unblock/{room_id}',[BlockedRoomController::class,'UnBlockedRoom'])->name('unblock');
    Route::resource('/houses',HouseController::class)->only(['index']);
    Route::resource('/houses/{house_id}',RoomController::class)->only(['index']);
    Route::view('/houses/{house_id}/{room_id}','manager.student_regstration');
    Route::resource('/switch_room', SwitchRoomController::class)->only(['index','update']);
    Route::post('/quittance_by_manager/{contract_id}',[QuittanceController::class,'quittance_by_manager'])->name('quittanceByManager');
    Route::resource('/supervisor', SupervisorController::class)->only(['index','update']);
    Route::get('/viewroom/{room_id}',ManagerOrders::class);
    Route::get('/viewstudent/{student_id}',ManagerOrders::class);
    Route::resource('/advertisments',AdvertismentController::class)->only(['index','store']);
});





Route::group(['middleware'=>'role:student','prefix'=>'student','as'=>'student.'],function(){
         Route::view('/','student.student');
         Route::resource('/houses',HouseController::class)->only(['index']);
         Route::resource('/houses/{house_id}', RoomController::class)->only(['index']);
         Route::post('/regestroom/{roomid}',[ContractController::class,'regestRoom']);
         Route::resource('/maintenance',MaintenanceController::class)->only(['store']);
         Route::get('/myOrder',[OrderController::class,'index'])->name('order');
         Route::resource('/quittance',QuittanceController::class)->only(['store']);
         Route::post('/switch_room/{room_id}',[SwitchRoomController::class,'store']);
         Route::resource('/advertisments',AdvertismentController::class)->only(['index']);
});

Route::group(['middleware'=>'role:supervisor','prefix'=>'supervisor','as'=>'supervisor.'],function(){
         Route::view('/','supervisor.supervisor');
         Route::resource('/maintenance',MaintenanceController::class)->only(['index','update']);
         Route::resource('/quittance',QuittanceController::class)->only(['index','update']);
         Route::resource('/switch_room',SwitchRoomController::class)->only(['index','update']);
         Route::resource('/advertisments',AdvertismentController::class)->only(['index']);
});

});


Route::redirect('/', '/login', 301);
Route::get('/test',[testController::class,'s']);

Route::get('/test',[testController::class,'index']);

app/Http/Livewire/Advirtesment.php
<?php

namespace App\Http\Livewire;

use App\Models\Advertisment;
use Livewire\Component;

class Advirtesment extends Component
{
    public $searchQuery;
    public $addressed_to;
    public function mount(){
       $this->searchQuery="";
       $this->addressed_to="";
    }

    public function render()
    {
        if(auth()->user()->type=='manager')
        {
                $advertisments=Advertisment::when($this->searchQuery!='',
               function ($query){
                   $query->where('title','like','%'.$this->searchQuery.'%');
                 })->when($this->addressed_to!='',
                 function($query){
                 $query->where('addressed_to','=',$this->addressed_to);
                 })->get();

        }
            
        else{
            if(auth()->user()->type=='student'){
            $advertisments=Advertisment::where('addressed_to','=','student')->orwhere('addressed_to','=','all')->when($this->searchQuery!='',
        function ($query){
            $query->where('title','like','%'.$this->searchQuery.'%');
        })->latest()->get();}
        else{
            $advertisments=Advertisment::where('addressed_to','=','supervisor')->orwhere('addressed_to','=','all')->when($this->searchQuery!='',
            function ($query){
                $query->where('title','like','%'.$this->searchQuery.'%');
            })->latest()->get();  
        }
        }
        return view('livewire.advirtesment',['advetisments'=>$advertisments]);
    }
}

app/Http/Livewire/ManagerOrders.php
<?php

namespace App\Http\Livewire;

use App\Models\Contract;
use App\Models\Maintenance;
use App\Models\Quittance;
use App\Models\Student;
use App\Models\SwitchRoom;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\UnauthorizedException;
use Livewire\Component;

class ManagerOrders extends Component
{
   
    public $orders2;
    public function mount(){
    $student_id=request('student_id');
    $room_id=request('room_id');
    $contracts="";
    $this->orders2=collect();
    if(isset($student_id)){
        if(Auth()->user()->type=="sutdent"){
            if(Auth()->user()->user_id!=$student_id){
               abort(403);
            }
        }
        $contracts=Contract::withTrashed()->where('student_id',$student_id)->get();
    }
    else{
        $contracts=Contract::withTrashed()->where('room_id',$room_id)->get();
        }
        $state=array(
            "in_manager"=>"عند الادارة",
            "in_supervisor"=>"عند مشرف السكن",
            "accepted"=>'مقبول',
            "active_now"=>'جاري',
            "rejected"=>'مرفوض',
            'deleted'=>'منتهي'
        );
        $img=array(
            "in_manager"=>"عند الادارة",
            "in_supervisor"=>"عند مشرف السكن",
            "accepted"=>'مقبول',
            "active_now"=>'جاري',
            "rejected"=>'مرفوض',
            'deleted'=>'انتهى'
        );
        $color=array(
            "in_manager"=>"var(--gray-color)",
            "in_supervisor"=>"var(--gray-color)",
            "accepted"=>'var(--green-color)',
            "active_now"=>'var(--green-color)',
            "rejected"=>'var(--red-color)',
            'deleted'=>'var(--red-color)'
        );
    foreach($contracts as $contract){
        $maintenances=Maintenance::where('contract_id','=',$contract->id)->get();
        $switchRooms=SwitchRoom::where('contract_id','=',$contract->id)->get();
        $quittances=Quittance::where('contract_id','=',$contract->id)->get();
        $this->orders2->push(
            [
                
                'order_state'=>$state[$contract->contract_state],
                'order_id'=>$contract->id,
                'created_at'=>$contract->created_at,
                'name'=>'عقد',
                'color'=>$color[$contract->contract_state],
                'img'=>$img[$contract->contract_state],
            ]
        );
        foreach($maintenances as $maintenance){
            $this->orders2->push(
                [
                    'order_state'=>$state[$maintenance->maintenace_state],
                    'order_id'=>$maintenance->id,
                    'created_at'=>$maintenance->created_at,
                    'name'=>'صيانة',
                    'color'=>$color[$maintenance->maintenace_state],
                    'img'=>$img[$maintenance->maintenace_state],
                ]
            );
        }
        foreach($quittances as $quittance){
            $this->orders2->push(
                [
                    'order_state'=>$state[ $quittance->quittance_state],
                    'order_id'=> $quittance->id,
                    'created_at'=> $quittance->created_at,
                    'name'=>'براءة ذمة',
                    'color'=>$color[$quittance->quittance_state],
                    'img'=>$img[$quittance->quittance_state],
                ]
            );
        }
        foreach($switchRooms as $switchRoom){
            $this->orders2->push(
                [
                    'order_state'=>$state[$switchRoom->switch_room_state],
                    'order_id'=> $switchRoom->id,
                    'created_at'=> $switchRoom->created_at,
                    'name'=>'تبديل',
                    'color'=>$color[$switchRoom->switch_room_state],
                    'img'=>$img[$switchRoom->switch_room_state],
                ]
            );
        }
     
    }
    $this->orders2 = collect( $this->orders2)->sortBy('created_at')->reverse();
    dd($this->orders2);
    }
    public function render()
    {
        return view('livewire.manager-orders');
    }
}

app/Http/Livewire/Orders.php
<?php

namespace App\Http\Livewire;

use App\Models\Contract;
use App\Models\Maintenance;
use App\Models\Quittance;
use App\Models\SwitchRoom;
use Illuminate\Support\Arr;
use Livewire\Component;
use Stringable;

use function PHPUnit\Framework\returnSelf;

class Orders extends Component
{
   public $orders2;
    public $searchQuery;
    public $type;
    public function mount(){
        $student_id=Auth()->user()->user_id;
        $contract=Contract::where([['student_id','=',$student_id],['contract_state','=','active_now']])->first();
        $maintenances=Maintenance::where('contract_id','=',$contract->id)->get();
        $switchRooms=SwitchRoom::where('contract_id','=',$contract->id)->get();
        $quittances=Quittance::where('contract_id','=',$contract->id)->get();
       
        $state=array(
            "in_manager"=>"عند الادارة",
            "in_supervisor"=>"عند مشرف السكن",
            "accpeted"=>'مقبول',
            "active_now"=>'جاري',
            "rejected"=>'مرفوض',
            'deleted'=>'محذوف'
        );
        $this->orders2=collect();
        foreach($maintenances as $maintenance){
            $this->orders2->push(
                [
                    'order_state'=>$state[$maintenance->maintenace_state],
                    'order_id'=>$maintenance->id,
                    'created_at'=>$maintenance->created_at,
                    'name'=>'صيانة'
                ]
            );
        }
        foreach($quittances as $quittance){
            $this->orders2->push(
                [
                    'order_state'=>$state[ $quittance->quittance_state],
                    'order_id'=> $quittance->id,
                    'created_at'=> $quittance->created_at,
                    'name'=>'براءة ذمة'
                ]
            );
        }
        foreach($switchRooms as $switchRoom){
            $this->orders2->push(
                [
                    'order_state'=>$state[$switchRoom->switch_room_state],
                    'order_id'=> $switchRoom->id,
                    'created_at'=> $switchRoom->created_at,
                    'name'=>'تبديل'
                ]
            );
        }
        $this->orders2 = collect( $this->orders2)->sortBy('created_at')->reverse();
      $this->searchQuery="";
      $this->type="";
       }
    public function render()
    {

       $orders=$this->orders2->filter(function ($item)  {
        return  (stristr($item['name'], $this->searchQuery)||stristr($item['order_id'], $this->searchQuery))&&(stristr($item['name'], $this->type));
    })->sortBy('created_at')->reverse();
        return view('livewire.orders',['orders'=>$orders]);
    }
}

app/Http/Livewire/Rooms.php
<?php

namespace App\Http\Livewire;

use App\Models\Room;
use App\Models\Student;
use Livewire\Component;

class Rooms extends Component
{
    public $house_id;
    public $hasRoom;
    public $hasSwitchRoom;
    public  $hasActiveRoom;
    public $searchQuery;
    public $orderQuery;
    public $emptyQuery;
    public function mount(){
        $this->house_id=request('house_id');
      if(Auth()->user()->type=='student'){
        $studnet=Student::find(Auth()->user()->user_id);
        $this->hasRoom=$studnet->hasRoom();
        $this->hasSwitchRoom=$studnet->hasSwitchRoom();
        $this->hasActiveRoom=($studnet->getActiveContract->count()>0);
      }
      $this->searchQuery="";
      $this->orderQuery="";
      $this->emptyQuery="";
    }
    public function render()
    {
        $rooms=Room::where('house_id','=',$this->house_id)->when(
            Auth()->user()->type=='student',function($query){
                $query->where('blocked_now','=','0');
            }
        )->when(
            $this->searchQuery!="",function($query){
                $query->where('room_name','like','%'.$this->searchQuery.'%');
            }
        )->when(
            $this->orderQuery!="",function($query){
                $query->orderBy($this->orderQuery);
             
            }
        )->get()->filter(function($item){
            if($this->emptyQuery!=""){
            if($this->emptyQuery=="full"){
                return $item['emp']==0;
            }
            else if($this->emptyQuery=="empty"){
                return $item['emp']==$item['capacity'];
            }
            else{
                return $item['emp']>0&&$item['emp']<$item['capacity'];
            }}
            else{
                return true;
            }
        });
      
      
        return view('livewire.rooms',['rooms'=>$rooms]);
    }
}

app/Http/Livewire/Supervisors.php
<?php

namespace App\Http\Livewire;

use App\Models\House;
use App\Models\User;
use Livewire\Component;

class Supervisors extends Component
{
    public $searchQuery;
    public $femaleHouses;
    public $maleHouses;
    public $houseQuery;
    public function mount(){
        $this->femaleHouses=House::where('gender','=','female')->get();
        $this->maleHouses=House::where('gender','=','male')->get();
        $this->searchQuery="";
    }
    public function render()
    {
        $supervisors=User::where('type','=','supervisor')->when(
            $this->searchQuery !="",function($query){
                $query->where('name','like','%'.$this->searchQuery.'%')->orWhere('user_id','like','%'.$this->searchQuery.'%');
            }
        )->get()->filter(function($item){
            if($this->houseQuery!=""){
            if($this->houseQuery=="without house"){
                return $item['house_id']==null;
            }
            else
            return $item['house_id']==$this->houseQuery;
          }
            else{
                return true;
            }
        });
        return view('livewire.supervisors',['supervisors'=>$supervisors]);
    }
}

app/Http/Livewire/Users.php
<?php

namespace App\Http\Livewire;

use App\Models\User;
use Livewire\Component;

class Users extends Component
{
  
    public $searchQuery;
    public $type;
    public function mount(){
       $this->searchQuery="";
     $this->type="";
    }
    public function render()
    {
    
        $users=User::where('type','!=','student')->when($this->searchQuery!='',
        function ($query){
            $query->where('name','like','%'.$this->searchQuery.'%')->orWhere('user_id','like','%'.$this->searchQuery.'%');
        })->when($this->type!='',
        function($query){
            $query->where('type','=',$this->type);
        })->get();
        return view('livewire.users',['users'=>$users]);
    }
}

resources/views/livewire/advirtesment.blade.php
<div>
    <input wire:model.debounce.500ms="searchQuery" type="text" placeholder="بحث" >
    @if (auth()->user()->type=='manager')
    <select wire:model="addressed_to">
        <option value="" selected hidden> اختر  الجهة المرسل لها </option>
        <option value="">الكل</option>
        <option value="all"> الطلاب والمشرفين </option>
        <option value="student"> الطلاب</option>
        <option value="supervisor"> المشرفين </option>
    </select>
    @endif
    <div class="welcome bg-white rad-10 ">
        <div class="intro p-20 d-flex space-between bg-eee">
            <div class="latest_news p-20 bg-white rad-10 txt-c">
                <div class="container">
                    @if(auth()->user()->type=='manager')
                    <div class="title">
                        <h2> الإعلانات</h2>
                         <button class="ads-plus" onclick="openForm('adv-form')" > 
                             إعلان جديد
                            <i class="fa-solid fa-plus "></i>
                        </button>
                    </div>
                    @forelse ($advetisments as $advertisment)
                    <div class="list" onclick="openForm('{{ $advertisment->id }}')">
                        <div class="person">
                            <div class="name">
                                @if ($advertisment->addressed_to=='all')
                                <img src="{{ asset('images/319-3192009_team-group-of-people-animated-png-transparent-png.png') }}" alt="">
                                @elseif($advertisment->addressed_to=='student')
                                <img src="{{ asset('images/IMG-20230125-WA0029.jpg') }}" alt="">
                                @elseif($advertisment->addressed_to=='supervisor')
                                <img src="{{ asset('images/IMG-20230125-WA0037.jpg') }}" alt="">
                                @endif
                                <a href="javascript:{}" >{{$advertisment->title}} </a>
                            </div>
                            <div class="net-worth">
                                <span>{{ $advertisment->created_at->shortRelativeDiffForHumans() }}</span>
                            </div>
                        </div>
                    </div>
                        @empty
                        <span> لايوجد أي إعلانات حالياً</span>
                    @endforelse
                   @endif


                   @if(auth()->user()->type=='student')
                   <div class="title">
                    <h2> الإعلانات</h2>
                </div>
                @forelse ($advetisments as $advertisment)
                <div class="list"  onclick="openForm('{{ $advertisment->id }}')">
                    <div class="person">
                        <div class="name">
                            @if ($advertisment->addressed_to=='all')
                            <img src="{{ asset('images/319-3192009_team-group-of-people-animated-png-transparent-png.ifif') }}" alt="">
                            @else
                            <img src="{{ asset('images/IMG-20230125-WA0029.jpg') }}" alt="">
                            @endif
                            <a href="javascript:{}">{{$advertisment->title}} </a>
                        </div>
                        <div class="net-worth">
                            <span>{{ $advertisment->created_at->shortRelativeDiffForHumans() }}</span>
                        </div>
                    </div>
                </div>
                    @empty
                    <span> لايوجد أي إعلانات حالياً</span>
                @endforelse

                   @endif
                   @if(auth()->user()->type=='supervisor')
                                <div class="title">
                                    <h2> الإعلانات</h2>
                                </div>
                                @forelse ($advetisments as $advertisment)
                                <div class="list"  onclick="openForm('{{ $advertisment->id }}')">
                                    <div class="person">
                                        <div class="name">
                                            @if ($advertisment->addressed_to=='all')
                                            <img src="{{ asset('images/319-3192009_team-group-of-people-animated-png-transparent-png.ifif') }}" alt="">
                                            @else
                                            <img src="{{ asset('images/IMG-20230125-WA0037.jpg') }}" alt="">
                                            @endif
                                            <a href="javascript:{}">{{$advertisment->title}} </a>
                                        </div>
                                        <div class="net-worth">
                                            <span>{{ $advertisment->created_at->shortRelativeDiffForHumans() }}</span>
                                        </div>
                                    </div>
                                </div>
                                    @empty
                                    <span> لايوجد أي إعلانات حالياً</span>
                                @endforelse
                   @endif
                </div>



            </div>


        </div>
    </div>
</div>

resources/views/livewire/manager-orders.blade.php
<div>
    {{-- Do your work, then step back. --}}
</div>

resources/views/livewire/rooms.blade.php
<div>
    <input wire:model.debounce.500ms="searchQuery" type="text" placeholder="بحث" class="input">
    <select wire:model="orderQuery">
    <option value="">ترتيب حسب</option>
    <option value="price">سعر</option>
    <option value="space">مساحة</option>
    <option value="capacity">سعة</option>
    </select>
    <select wire:model="emptyQuery">
    <option value="">شواغر الغرفة</option>
    <option value="full">ممتلئة</option>
    <option value="empty">فارغة تماماً</option>
    <option value="half empty">فارغة جزئياً</option>
    </select>
    <div class="wrapper d-flex gap-20 ">
        <div class="intro p-20   bg-eee">
            @if (Auth()->user()->type=='student')

            @foreach ($rooms as $room)
            @if($room->getEmpty() >0)
            <div class="container">
                <div class="product">
                    <div class="info">
                        <h2> {{ $room->room_name}}</h2>
                        <ul>
                            <li><strong>المساحة : </strong>{{ $room->space }} </li>
                            <li><strong>السعة : </strong>{{ $room->capacity }}</li>
                            <li><strong>الشواغر: </strong> {{ $room->getEmpty() }}</li>
                            <li><strong>الاتجاه: </strong>{{ $room->direction }}</li>
                            <li><strong>السعر: </strong> {{ $room->price }}</li>
                        </ul>
                        @if(!$hasRoom)

                        <form method="POST" action="/student/regestroom/{{ $room->id }}" id="{{ $room->id }}">
                            @csrf
                            <button class="btn">
                                <a href="javascript:{}" onclick="confirm({{ $room->id }})">
                                    تسجيل
                                </a>
                            </button>
                        </form>
                        @elseif (!$hasSwitchRoom && $hasActiveRoom)
                        <form method="POST" action="/student/switch_room/{{ $room->id }}" id="{{ $room->id }}">
                            @csrf
                            <button class="btn">
                                <a href="javascript:{}" onclick="confirm({{ $room->id }})">
                                    تبديل
                                </a>
                            </button>
                        </form>
                        @endif
                    </div>
                </div>
            </div>
            @endif
            @endforeach
            @endif
            @if(Auth()->user()->type=='manager')
            @foreach ($rooms as $room)
            <div class="container">
                <div class="product">
                    <div class="info">
                        <h2> {{ $room->room_name}}</h2>
                        <ul>
                            <li><strong>المساحة : </strong>{{ $room->space }} </li>
                            <li><strong>السعة : </strong>{{ $room->capacity }}</li>
                            <li><strong>الشواغر: </strong> {{ $room->getEmpty() }}</li>
                            <li><strong>الاتجاه: </strong>{{ $room->direction }}</li>
                            <li><strong>السعر: </strong> {{ $room->price }}</li>
                        </ul>
                        @if($room->blocked_now==0)
                        <button class="btn" onclick="confirm3('{{ $room->id }}')" type="submit">حجب </button>
                        <form method="POST" action="{{ route('manager.block',$room->id) }}" id="{{ $room->id }}">
                            @csrf
                        </form>
                        @else
                        <button class="btn" type="submit"> <a href="javascript:{}"
                                onclick="confirm2('{{$room->id}}')">إلغاء الحجب </a></button>
                        <form method="POST" action="{{ route('manager.unblock',$room->id) }}" id="{{  $room->id  }}">
                            @csrf
                        </form>
                        @endif
                        <button class="btn"> <a href="">عقود </a>
                        </button>
                        <button class="btn"> <a
                                href="{{  request()->segment(count(request()->segments())) }}/{{ $room->id }}">
                                تسجيل</a>
                        </button>
                    </div>
                </div>
            </div>
            @endforeach
            @endif
            @if (Auth()->user()->type=='admin')
            @foreach ($rooms as $room)
            <div class="container">
                <div class="product">
                    <div class="info">
                        <h2> {{ $room->room_name}}</h2>
                        <ul>
                            <li><strong>المساحة : </strong>{{ $room->space }} </li>
                            <li><strong>السعة : </strong>{{ $room->capacity }}</li>
                            <li><strong>الشواغر: </strong> {{ $room->getEmpty() }}</li>
                            <li><strong>الاتجاه: </strong>{{ $room->direction }}</li>
                            <li><strong>السعر: </strong> {{ $room->price }}</li>
                        </ul>
                        <button class="btn" title="تعديل"> <a href="javascript:{}"
                                onclick="openForm('{{ $room->id }}')"><i class="fa-solid fa-pen"></i> </a>
                        </button>
                        <button class="btn remove-all-styles"  title="حذف"> <a href="javascript:{}"
                                onclick="confirm('{{ $room->id }}d')"><i
                                    class="fa-solid fa-trash remove-all-styles"></i></a>
                            <form id="{{ $room->id }}d" method="POST" action="/admin/rooms/{{ $room->id }}"
                                class="remove-all-styles ">
                                @csrf
                                @method('DELETE')
                            </form>
                        </button>
                    </div>
                </div>
            </div>
            @endforeach
            <div class="container">
                <div class="product-add">
                    <div class="info-add">
                        <button class="btn-add" title="إضافة غرفة"> <a href="javascript:{}"
                                onclick="openForm('add-form')"><i class="fa-solid fa-plus"></i> </a></button>
                    </div>
                </div>
            </div>
            @endif
        </div>
    </div>
</div>

resources/views/livewire/users.blade.php
<div >
<input wire:model.debounce.500ms="searchQuery" type="text" placeholder="بحث" >
<select name="type" wire:model="type" >
    <option value="">all</option>
    <option value="admin">admin</option>
    <option value="manager">manager</option>
    <option value="supervisor">supervisor</option>
</select>

<div class="container">

 
    <table>
        <thead>
            <tr>
                <th> رقم المستخدم</th>
                <th> اسم المستخدم</th>
                <th> دور المستخدم</th>
                <th>جنس المستخدم</th>
                <th> الأحداث</th>


            </tr>
        </thead>
        @foreach ($users as $user)
        <tbody>
            <tr>
                <td> {{ $user->user_id }}</td>
                <td> {{ $user->name }}</td>
                <td>{{ $user->type }} </td>
                <td>{{ $user->gender }}</td>
                <td>
                    <a href="javascript:{}" onclick="openForm('{{ $user->id }}')"> <i class="fa-solid fa-pen fa-fw" style="color:var(--move1-color)"></i> </a>
               
                   <a href="javascript:{}" onclick="confirm('{{ $user->id }}d')"> <i class="fa-solid fa-trash fa-fw" style="color:var(--red-color)"></i></a>
                        <form id="{{ $user->id }}d" method="POST" action='{{ route('admin.user.destroy',$user->id) }}' style="all: revert;display:none">
                            @csrf
                            @method('DELETE')
                      </form>
                    
                </td>

            </tr>
        </tbody>
        @endforeach
    </table>
</div>
</div>